Plugin.define do
    name "axcms_net" 
    authors [
        "winezero",

    ]
    version "0.1"
    matches [ { :search => "headers", :text => 'AxCMS.net'   },
    { :text => 'Generated by AxCMS.net'   },
    { :text => 'content="AxCMS.net'   }
]
end