Plugin.define do
name "BloofoxCMS"
authors [
  "Brendan Coles <bcoles@gmail.com>", 

]
version "0.1"
description "bloofoxCMS is a free open source content management system (CMS). bloofoxCMS is a small and easy to use CMS."
website "http://bloofox.com/"
dorks [
'"Powered by bloofoxCMS"'
]
matches [
    {:regexp=>/<!--[\r\n\s]+This Website was generated by bloofoxCMS.[\r\n\s]+bloofoxCMS is open source published under the gnu gpl. Visit www.bloofox.com for more details![\r\n\s]+Copyrights \(c\) 2006-2007 by Alexander Lang[\r\n\s]+\/\/-->/},
    {:regexp=>/Powered by <a href="http:\/\/www.bloofox.com">bloofoxCMS<\/a>/i },
    {:text=>'Powered by <a href="http://www.bloofox.com'},
    {:text=>'content="bloofoxCMS'},
    {:version=>/<meta name="generator" content="bloofoxCMS ([\d\.]+)" \/>/}
]
end
