Plugin.define do
    name "doxygen" 
    authors [
        "winezero",

    ]
    version "0.1"
    matches [ { :regexp => /(?:<!-- Generated by Doxygen ([\d.]+)|<link[^>]+doxygen\.css)/,:offset => 1  },
    { :regexp => /Doxygen ([\d.]+)/,:offset => 1, :search => 'body'  }
]
end