Plugin.define do
name "Hiki"
authors [
  "Brendan Coles <bcoles@gmail.com>", 

]
version "0.1"
description "Hiki is a powerful and fast wiki clone written in Ruby."
website "http://hikiwiki.org/en/"
dorks [
'"Generated by Hiki" "Powered by Ruby"'
]
matches [
    {:text=>'/hiki_base.css'},
    {:text=>'<html><head><title>Hiki Error</title></head><body>'},
    {:text=>'by <a href="http://hikiwiki.org/'},
    {:text=>'content="Hiki'},
    {:version=>/<div class="footer">Generated by <a href="http:\/\/hikiwiki.org\/">Hiki<\/a> ([^\s]+) \([\d]{4}-[\d]{2}-[\d]{2}\)/},
    {:version=>/<meta name="generator" content="Hiki ([^"^\s]+)">/}
]
passive do
	m=[]
	if @body =~ /<div class="footer">Generated by <a href="http:\/\/hikiwiki.org\/">Hiki<\/a>/ and @body =~ /Powered by <a href="http:\/\/www\.ruby-lang\.org\/">(Ruby)<(\/)a> ([^\s]+) \([\d]{4}-[\d]{2}-[\d]{2}\)/
		m << { :string=>@body.scan(/Powered by <a href="http:\/\/www\.ruby-lang\.org\/">(Ruby)<(\/)a> ([^\s]+) \([\d]{4}-[\d]{2}-[\d]{2}\)/).flatten }
	end
	m
end
end
