Plugin.define do
    name "kingcms" 
    authors [
        "winezero",

    ]
    version "0.1"
    matches [ { :text => 'Powered by KingCMS'   },
    { :text => 'content="KingCMS'   },
    { :text => 'kingcms'   },
    { :url => '/Article/index.asp', :text => 'kingcms'   },
    { :url => '/EasyArticle/index.asp', :text => 'kingcms'   },
    { :url => '/INSTALL.asp', :text => 'kingcms'   },
    { :url => '/INSTALL.php', :text => 'kingcms'   },
    { :url => '/License.txt', :text => 'kingcms'   },
    { :url => '/Tools/index.asp', :text => 'kingcms'   },
    { :url => '/ad.asp', :text => 'kingcms'   },
    { :url => '/ad/index.asp', :text => 'kingcms'   },
    { :url => '/admin.asp', :text => 'kingcms'   },
    { :url => '/admin/Article/index.asp', :text => 'kingcms'   },
    { :url => '/admin/system/create.asp', :text => 'kingcms'   },
    { :url => '/admin/system/images/logo.png', :md5 => 'ef207bd06faac743f879dd7bc5557a13'   },
    { :url => '/admin/system/images/topbg.png', :md5 => '272cc3f4a73ae8e7bc36cf7c38a3644a'   },
    { :url => '/admin/webftp/index.asp', :text => 'kingcms'   },
    { :url => '/api/alipay.php', :text => 'kingcms'   },
    { :url => '/block/core.class.php', :text => 'kingcms'   },
    { :url => '/collect.asp', :text => 'kingcms'   },
    { :url => '/collect/index.asp', :text => 'kingcms'   },
    { :url => '/comment/index.asp', :text => 'kingcms'   },
    { :url => '/counter.asp', :text => 'kingcms'   },
    { :url => '/create.asp', :text => 'kingcms'   },
    { :url => '/dbquery/core.class.php', :text => 'kingcms'   },
    { :url => '/dbquery/language/zh-cn.xml', :text => 'kingcms'   },
    { :url => '/download/index.asp', :text => 'kingcms'   },
    { :url => '/feedback/core.class.php', :text => 'kingcms'   },
    { :url => '/images/logo.png', :md5 => '3c8d1927c1c1bde1f126b202cb7b1a2f'   },
    { :url => '/images/logo.png', :md5 => '5d341f4f03aff5421b0b5bd4ebc82400'   },
    { :url => '/images/style.css', :text => 'kingcms'   },
    { :url => '/inc/config.asp', :text => 'kingcms'   },
    { :url => '/install.php', :text => 'kingcms'   },
    { :url => '/install.sql', :text => 'kingcms'   },
    { :url => '/language/zh-cn.xml', :text => 'kingcms'   },
    { :url => '/library/template.class.php', :text => 'kingcms'   },
    { :url => '/link.asp', :text => 'kingcms'   },
    { :url => '/link/index.asp', :text => 'kingcms'   },
    { :url => '/login.asp', :text => 'kingcms'   },
    { :url => '/main.asp', :text => 'kingcms'   },
    { :url => '/menu.asp', :text => 'kingcms'   },
    { :url => '/movie/index.asp', :text => 'kingcms'   },
    { :url => '/onepage/index.asp', :text => 'kingcms'   },
    { :url => '/page/Tools/fun.asp', :text => 'kingcms'   },
    { :url => '/page/addlink.asp', :text => 'kingcms'   },
    { :url => '/page/system/inc/fun.js', :text => 'kingcms'   },
    { :url => '/page/webftp/fun.asp', :text => 'kingcms'   },
    { :url => '/passport/index.asp', :text => 'kingcms'   },
    { :url => '/system/images/fun.js', :text => 'kingcms'   },
    { :url => '/system/images/logo.png', :md5 => '050aa01fafbc432c5b97893282784e61'   },
    { :url => '/system/images/logo.png', :md5 => 'c38eda6e439da7e728c12822e1170615'   },
    { :url => '/system/js/jquery.kc.js', :text => 'kingcms'   },
    { :url => '/template.asp', :text => 'kingcms'   },
    { :url => '/template/default.htm', :text => 'kingcms'   },
    { :url => '/user.asp', :text => 'kingcms'   },
    { :url => '/user/face/2.gif', :md5 => '059014cbce00d3028cbb3a74eb20e837'   },
    { :url => '/user/face/2.gif', :md5 => '806b062dbb2377d05cad134d53d706a1'   },
    { :url => '/user/index.php', :text => 'kingcms'   },
    { :url => '/webftp.asp', :text => 'kingcms'   },
    { :url => '/webftp/index.asp', :text => 'kingcms'   }
]
end