Plugin.define do
name "ModLogAn"
authors [
  "Brendan Coles <bcoles@gmail.com>", 

]
version "0.1"
description "Modlogan is a modular logfile analyzer which is currently able to parse ftp-, webserver and squid logs."
website "http://modlogan.com/"
dorks [
'"Output generated by modlogan"'
]
matches [
{ :text=>'<link rel="stylesheet" href="modlogan.css" type="text/css" />' },
{ :text=>'<LINK REL=STYLESHEET HREF="modlogan.css" type="text/css"></HEAD>' },
{ :version=>/Output generated by <a href="http:\/\/www\.(modlogan\.org|kneschke\.de\/projekte\/modlogan\/)">modlogan ([^\s^<]+)<\/a>/, :offset=>1 },
]
end
