Plugin.define do
    name "munin" 
    authors [
        "winezero",

    ]
    version "0.1"
    matches [ { :text => 'Auto-generated by Munin'   },
    { :text => 'munin-month.html'   }
]
end