Plugin.define do
name "phpDocumentor"
authors [
  "Brendan Coles <bcoles@gmail.com>", 

]
version "0.1"
description "phpDocumentor, sometimes referred to as phpdoc or phpdocu, is the current standard auto-documentation tool for the php language. Similar to Javadoc, and written in php, phpDocumentor can be used from the command line or a web interface to create professional documentation from php source code."
dorks [
'intitle:"docBuilder - phpDocumentor web interface"'
]
matches [
    {:certainty=>75, :text=>'<title>docBuilder - phpDocumentor web interface</title>'},
    {:filepath=>/<input type="text" name="fileName" value="([^"]+)" size="60" class="text" \/>/},
    {:regexp=>/<!-- Generated by phpDocumentor/},
    {:text=>'<meta name="Description" content="Frameset for phpDcoumentor docBuilder web interface">'},
    {:text=>'<meta name="Description" content="Frameset for phpDocumentor docBuilder web interface">'},
    {:text=>'Generated by phpDocumentor'},
    {:version=>/	<title>\n		Form to submit to phpDocumentor v([^\s]+)	<\/title>/},
    {:version=>/<span class="title"><strong>docBuilder<\/strong> :: phpDocumentor v([^\s]+) Web Interface<\/span>/}
]
end
