Plugin.define do
name "Plesk"
authors [
  "Andrew Horton",

  "Brendan Coles <bcoles@gmail.com>", 

]
version "0.4"
description "Plesk is a web control panel"
website "http://www.parallels.com/products/plesk/"
dorks [
'intitle:"Default Parallels Plesk Panel Page"'
]
matches [
    {:certainty=>25, :text=>'if (window.plesk_promo.virtuozzo) {'},
    {:certainty=>75, :search=>"headers[server]", :regexp=>/sw-cp-server/},
    {:mmh3=>'-1050786453'},
    {:mmh3=>'-134375033'},
    {:mmh3=>'-981606721'},
    {:name=>"copyright parallels", :certainty=>25, :regexp=>/&copy; Copyright [\d]{4}\-[\d]{4}, Parallels</},
    {:name=>"h1 plesk link", 
:text=>'<h1><a class="product-logo" href="http://www.parallels.com/plesk/" title="Parallels Plesk Panel">Parallels Plesk Panel</a></h1>'},
    {:name=>"logo gif", :regexp=>/<img src='def_plesk_logo\.gif' alt="Plesk logo"/},
    {:name=>"poweredBy parallels", 
:regexp=>/<a target="_blank" href="http:\/\/www\.parallels\.com"><img src="[^"]+\/parallels_powered\.gif" title="Powered by Parallels&trade;"><\/a>/},
    {:regexp=>/This page (was|is) generated by <a href="http:\/\/www\.parallels\.com\/(en\/products\/)?plesk\/">Parallels Plesk Panel<\/a>/},
    {:regexp=>/^Plesk(?:L|W)in/, :search=>'headers[x-powered-by]'},
    {:regexp=>/common\.js\?plesk/, :search=>'body'},
    {:search=>"headers[x-powered-by]", :string=>/Plesk([WL]in)/},
    {:search=>'headers[x-powered-by-plesk]', :regexp=>/^Plesk/},
    {:text=>'<div class="poweredBy"><a target="_blank" href="http://www.swsoft.com/en/products/plesk/'},
    {:text=>'<h1>This is the Plesk&#153; default page</h1>'},
    {:text=>'<p>For more information please contact <!--@adminemail@-->'},
    {:text=>'<title>Default PLESK Page</title>'},
    {:text=>'<title>Default Parallels Plesk Panel Page</title>'},
    {:text=>'This page is autogenerated by <a target="_blank" href="http://www.swsoft.com/en/products/plesk/">Plesk'},
    {:url=>"/", :text=>'</html><!--______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________IE error page size limitation______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________-->'},
    {:url=>"/", :version=>/<script language="javascript" type="text\/javascript" src="\/javascript\/common\.js\?plesk_version=psa-([^\s^"]+)"\/?>/},
    {:url=>"favicon.ico", :md5=>"2cee5e3ce2f5c4640a68fc208c286494"}
]
end
