Plugin.define do
name "Pygopherd"
authors [
  "Brendan Coles <bcoles@gmail.com>", 

]
version "0.1"
description "An open source multi-protocol gopher server written in Python. Also works as an HTTP and WAP server."
website "http://quux.org:70/devel/gopher/pygopherd"
dorks [
'"server top" "view with gopher" "Generated by Pygopherd"'
]
matches [
{ :text=>'<BR>Generated by <A HREF="http://www.quux.org/devel/gopher/pygopherd">PyGopherd</A>' },
{ :regexp=>/<HTML><HEAD><TITLE>Selector Not Found<\/TITLE>[\s]+<H1>Selector Not Found<\/H1>/ },
]
end
