Plugin.define do
name "SearchFitShoppingCart"
authors [
  "Andrew Horton",

]
version "0.3"
description "Commercial ecommerce system written in PHP"
website "http://www.searchfit.com/shopping-cart-features.htm"
matches [
{:text=>"This Website is generated by SearchFit Shopping Cart"},
{:text=>'<a class="footer_link_system" target="_blank" style="font-size: 10px;" href="http://www.searchfit.com/'},
{:text=>'new SearchFitAnalytics("'},
{:version=>/This Website is generated by SearchFit Shopping Cart v([^ ]+)/,  :name=>"version" } 
]
end
