Plugin.define do
name "Utopia-News-Pro"
authors [
  "Brendan Coles <bcoles@gmail.com>", 

]
version "0.1"
description "Utopia News Pro - news management system"
website "http://www.utopiasoftware.net/newspro/"
dorks [
'intitle:"Powered By Utopia News Pro" inurl:"news.php?action="'
]
matches [
{ :text=>'<meta name="generator" content="Utopia News Pro - http://www.utopiasoftware.net/"/>' },
{ :version=>/<div align="center" class="fbox smallfont">\s*<!-- Copyright -->\s*Powered By: <a href="about\.php[^"^>]*">Utopia News Pro<\/a> ([^<]+)</ },
{ :text=>'<!-- Beta: editnews2.php -->' },
{ :text=>'<div class="sf">News generated by <a href="http://www.utopiasoftware.net">Utopia News Pro</a></div>' },
{ :text=>'<!-- PrintNews.Bit -->' },
]
end
