Plugin.define do
name "Webalizer-Log"
authors [
  "Brendan Coles <bcoles@gmail.com>", 

]
version "0.1"
description "Webalizer is a fast, free web server log file analysis program. It produces highly detailed, easily configurable usage reports in HTML format, for viewing with a standard web browser."
website "http://www.webalizer.org/"
dorks [
'intitle:"Usage Statistics for" "Monthly Statistics" "Generated by Webalizer"'
]
matches [
{ :version=>/<!-- Generated by The Webalizer  Ver\. ([^\s]+) -->/ },
{ :version=>/<!-- Webalizer Version ([^\s]+) \(Mod: [\d]{1,2}-[a-zA-Z]{3}-[\d]{4}\) -->/ },
{ :version=>/<A HREF="http:\/\/www\.webalizer\.org\/"><STRONG>Webalizer Version ([^<]+)<\/STRONG><\/A>/ },
]
end
