Plugin.define do
name "WordpressSuperCache"
authors [
  "Patrik Wallstrom",

]
version "0.3"
description "Cache functionality for Wordpress - http://wordpress.org/extend/plugins/wp-super-cache/"
matches [
{:name=>"supercache comment",
:regexp=>/^<!-- Cached page generated by WP-Super-Cache on /}
]
end
